default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: askprojectd_development


test:
  <<: *default
  database: askprojectd_test


production:
  <<: *default
  database: askprojectd_production
  username: askprojectd
  password: <%= ENV["ASK_PROJECT_DATABASE_PASSWORD"] %>
